// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/news/proto/msg/admin_search_related_news.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminSearchRelatedNewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags        []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content     string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category    int32    `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory int32    `protobuf:"varint,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	PublishBy   string   `protobuf:"bytes,6,opt,name=publishBy,proto3" json:"publishBy,omitempty"`
	From        string   `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To          string   `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Offset      int32    `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit       int32    `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *AdminSearchRelatedNewsReq) Reset() {
	*x = AdminSearchRelatedNewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_admin_search_related_news_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminSearchRelatedNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchRelatedNewsReq) ProtoMessage() {}

func (x *AdminSearchRelatedNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_admin_search_related_news_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchRelatedNewsReq.ProtoReflect.Descriptor instead.
func (*AdminSearchRelatedNewsReq) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescGZIP(), []int{0}
}

func (x *AdminSearchRelatedNewsReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AdminSearchRelatedNewsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminSearchRelatedNewsReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AdminSearchRelatedNewsReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *AdminSearchRelatedNewsReq) GetSubCategory() int32 {
	if x != nil {
		return x.SubCategory
	}
	return 0
}

func (x *AdminSearchRelatedNewsReq) GetPublishBy() string {
	if x != nil {
		return x.PublishBy
	}
	return ""
}

func (x *AdminSearchRelatedNewsReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AdminSearchRelatedNewsReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AdminSearchRelatedNewsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AdminSearchRelatedNewsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_grpc_news_proto_msg_admin_search_related_news_proto protoreflect.FileDescriptor

var file_grpc_news_proto_msg_admin_search_related_news_proto_rawDesc = []byte{
	0x0a, 0x33, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x8e, 0x02, 0x0a, 0x19, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73,
	0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescOnce sync.Once
	file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescData = file_grpc_news_proto_msg_admin_search_related_news_proto_rawDesc
)

func file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescGZIP() []byte {
	file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescOnce.Do(func() {
		file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescData)
	})
	return file_grpc_news_proto_msg_admin_search_related_news_proto_rawDescData
}

var file_grpc_news_proto_msg_admin_search_related_news_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_news_proto_msg_admin_search_related_news_proto_goTypes = []interface{}{
	(*AdminSearchRelatedNewsReq)(nil), // 0: pb.AdminSearchRelatedNewsReq
}
var file_grpc_news_proto_msg_admin_search_related_news_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_news_proto_msg_admin_search_related_news_proto_init() }
func file_grpc_news_proto_msg_admin_search_related_news_proto_init() {
	if File_grpc_news_proto_msg_admin_search_related_news_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_news_proto_msg_admin_search_related_news_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminSearchRelatedNewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_news_proto_msg_admin_search_related_news_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_news_proto_msg_admin_search_related_news_proto_goTypes,
		DependencyIndexes: file_grpc_news_proto_msg_admin_search_related_news_proto_depIdxs,
		MessageInfos:      file_grpc_news_proto_msg_admin_search_related_news_proto_msgTypes,
	}.Build()
	File_grpc_news_proto_msg_admin_search_related_news_proto = out.File
	file_grpc_news_proto_msg_admin_search_related_news_proto_rawDesc = nil
	file_grpc_news_proto_msg_admin_search_related_news_proto_goTypes = nil
	file_grpc_news_proto_msg_admin_search_related_news_proto_depIdxs = nil
}
