// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/news/proto/msg/news_view_resp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsViewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	News *NewsView `protobuf:"bytes,3,opt,name=news,proto3" json:"news,omitempty"`
}

func (x *NewsViewResp) Reset() {
	*x = NewsViewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsViewResp) ProtoMessage() {}

func (x *NewsViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsViewResp.ProtoReflect.Descriptor instead.
func (*NewsViewResp) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_view_resp_proto_rawDescGZIP(), []int{0}
}

func (x *NewsViewResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewsViewResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NewsViewResp) GetNews() *NewsView {
	if x != nil {
		return x.News
	}
	return nil
}

type ListNewsViewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	News []*NewsView `protobuf:"bytes,3,rep,name=news,proto3" json:"news,omitempty"`
}

func (x *ListNewsViewResp) Reset() {
	*x = ListNewsViewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNewsViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewsViewResp) ProtoMessage() {}

func (x *ListNewsViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewsViewResp.ProtoReflect.Descriptor instead.
func (*ListNewsViewResp) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_view_resp_proto_rawDescGZIP(), []int{1}
}

func (x *ListNewsViewResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListNewsViewResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListNewsViewResp) GetNews() []*NewsView {
	if x != nil {
		return x.News
	}
	return nil
}

var File_grpc_news_proto_msg_news_view_resp_proto protoreflect.FileDescriptor

var file_grpc_news_proto_msg_news_view_resp_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x23,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x73, 0x56, 0x69, 0x65, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x65, 0x77,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77,
	0x73, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x6e, 0x65, 0x77, 0x73, 0x22, 0x5a, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77, 0x73, 0x56, 0x69, 0x65,
	0x77, 0x52, 0x04, 0x6e, 0x65, 0x77, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_news_proto_msg_news_view_resp_proto_rawDescOnce sync.Once
	file_grpc_news_proto_msg_news_view_resp_proto_rawDescData = file_grpc_news_proto_msg_news_view_resp_proto_rawDesc
)

func file_grpc_news_proto_msg_news_view_resp_proto_rawDescGZIP() []byte {
	file_grpc_news_proto_msg_news_view_resp_proto_rawDescOnce.Do(func() {
		file_grpc_news_proto_msg_news_view_resp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_news_proto_msg_news_view_resp_proto_rawDescData)
	})
	return file_grpc_news_proto_msg_news_view_resp_proto_rawDescData
}

var file_grpc_news_proto_msg_news_view_resp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_news_proto_msg_news_view_resp_proto_goTypes = []interface{}{
	(*NewsViewResp)(nil),     // 0: pb.NewsViewResp
	(*ListNewsViewResp)(nil), // 1: pb.ListNewsViewResp
	(*NewsView)(nil),         // 2: pb.NewsView
}
var file_grpc_news_proto_msg_news_view_resp_proto_depIdxs = []int32{
	2, // 0: pb.NewsViewResp.news:type_name -> pb.NewsView
	2, // 1: pb.ListNewsViewResp.news:type_name -> pb.NewsView
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_news_proto_msg_news_view_resp_proto_init() }
func file_grpc_news_proto_msg_news_view_resp_proto_init() {
	if File_grpc_news_proto_msg_news_view_resp_proto != nil {
		return
	}
	file_grpc_news_proto_msg_news_view_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsViewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_news_view_resp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNewsViewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_news_proto_msg_news_view_resp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_news_proto_msg_news_view_resp_proto_goTypes,
		DependencyIndexes: file_grpc_news_proto_msg_news_view_resp_proto_depIdxs,
		MessageInfos:      file_grpc_news_proto_msg_news_view_resp_proto_msgTypes,
	}.Build()
	File_grpc_news_proto_msg_news_view_resp_proto = out.File
	file_grpc_news_proto_msg_news_view_resp_proto_rawDesc = nil
	file_grpc_news_proto_msg_news_view_resp_proto_goTypes = nil
	file_grpc_news_proto_msg_news_view_resp_proto_depIdxs = nil
}
