// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/news/proto/msg/news_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order int32  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *NewsOrder) Reset() {
	*x = NewsOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsOrder) ProtoMessage() {}

func (x *NewsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsOrder.ProtoReflect.Descriptor instead.
func (*NewsOrder) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_order_proto_rawDescGZIP(), []int{0}
}

func (x *NewsOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsOrder) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type NewsOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*NewsOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *NewsOrders) Reset() {
	*x = NewsOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsOrders) ProtoMessage() {}

func (x *NewsOrders) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsOrders.ProtoReflect.Descriptor instead.
func (*NewsOrders) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_order_proto_rawDescGZIP(), []int{1}
}

func (x *NewsOrders) GetOrders() []*NewsOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type NewsOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg    string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Orders []*NewsOrder `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *NewsOrdersResp) Reset() {
	*x = NewsOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsOrdersResp) ProtoMessage() {}

func (x *NewsOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsOrdersResp.ProtoReflect.Descriptor instead.
func (*NewsOrdersResp) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_order_proto_rawDescGZIP(), []int{2}
}

func (x *NewsOrdersResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewsOrdersResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NewsOrdersResp) GetOrders() []*NewsOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_grpc_news_proto_msg_news_order_proto protoreflect.FileDescriptor

var file_grpc_news_proto_msg_news_order_proto_rawDesc = []byte{
	0x0a, 0x24, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x33, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x65, 0x77, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x5d, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x65, 0x77, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_news_proto_msg_news_order_proto_rawDescOnce sync.Once
	file_grpc_news_proto_msg_news_order_proto_rawDescData = file_grpc_news_proto_msg_news_order_proto_rawDesc
)

func file_grpc_news_proto_msg_news_order_proto_rawDescGZIP() []byte {
	file_grpc_news_proto_msg_news_order_proto_rawDescOnce.Do(func() {
		file_grpc_news_proto_msg_news_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_news_proto_msg_news_order_proto_rawDescData)
	})
	return file_grpc_news_proto_msg_news_order_proto_rawDescData
}

var file_grpc_news_proto_msg_news_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_news_proto_msg_news_order_proto_goTypes = []interface{}{
	(*NewsOrder)(nil),      // 0: pb.NewsOrder
	(*NewsOrders)(nil),     // 1: pb.NewsOrders
	(*NewsOrdersResp)(nil), // 2: pb.NewsOrdersResp
}
var file_grpc_news_proto_msg_news_order_proto_depIdxs = []int32{
	0, // 0: pb.NewsOrders.orders:type_name -> pb.NewsOrder
	0, // 1: pb.NewsOrdersResp.orders:type_name -> pb.NewsOrder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_news_proto_msg_news_order_proto_init() }
func file_grpc_news_proto_msg_news_order_proto_init() {
	if File_grpc_news_proto_msg_news_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_news_proto_msg_news_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_news_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_news_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_news_proto_msg_news_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_news_proto_msg_news_order_proto_goTypes,
		DependencyIndexes: file_grpc_news_proto_msg_news_order_proto_depIdxs,
		MessageInfos:      file_grpc_news_proto_msg_news_order_proto_msgTypes,
	}.Build()
	File_grpc_news_proto_msg_news_order_proto = out.File
	file_grpc_news_proto_msg_news_order_proto_rawDesc = nil
	file_grpc_news_proto_msg_news_order_proto_goTypes = nil
	file_grpc_news_proto_msg_news_order_proto_depIdxs = nil
}
