// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/news/proto/msg/news_tags.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag            string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Offset         int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeDeleted bool   `protobuf:"varint,4,opt,name=includeDeleted,proto3" json:"includeDeleted,omitempty"`
}

func (x *NewsTagReq) Reset() {
	*x = NewsTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsTagReq) ProtoMessage() {}

func (x *NewsTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsTagReq.ProtoReflect.Descriptor instead.
func (*NewsTagReq) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_tags_proto_rawDescGZIP(), []int{0}
}

func (x *NewsTagReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *NewsTagReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NewsTagReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NewsTagReq) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type NewsTagsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags   []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Offset int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *NewsTagsReq) Reset() {
	*x = NewsTagsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsTagsReq) ProtoMessage() {}

func (x *NewsTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsTagsReq.ProtoReflect.Descriptor instead.
func (*NewsTagsReq) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_tags_proto_rawDescGZIP(), []int{1}
}

func (x *NewsTagsReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NewsTagsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NewsTagsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type NewsTagsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *NewsTagsResp) Reset() {
	*x = NewsTagsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsTagsResp) ProtoMessage() {}

func (x *NewsTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_news_tags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsTagsResp.ProtoReflect.Descriptor instead.
func (*NewsTagsResp) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_news_tags_proto_rawDescGZIP(), []int{2}
}

func (x *NewsTagsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewsTagsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NewsTagsResp) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_grpc_news_proto_msg_news_tags_proto protoreflect.FileDescriptor

var file_grpc_news_proto_msg_news_tags_proto_rawDesc = []byte{
	0x0a, 0x23, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x74, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x73, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0x4f, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x48, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_news_proto_msg_news_tags_proto_rawDescOnce sync.Once
	file_grpc_news_proto_msg_news_tags_proto_rawDescData = file_grpc_news_proto_msg_news_tags_proto_rawDesc
)

func file_grpc_news_proto_msg_news_tags_proto_rawDescGZIP() []byte {
	file_grpc_news_proto_msg_news_tags_proto_rawDescOnce.Do(func() {
		file_grpc_news_proto_msg_news_tags_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_news_proto_msg_news_tags_proto_rawDescData)
	})
	return file_grpc_news_proto_msg_news_tags_proto_rawDescData
}

var file_grpc_news_proto_msg_news_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_news_proto_msg_news_tags_proto_goTypes = []interface{}{
	(*NewsTagReq)(nil),   // 0: pb.NewsTagReq
	(*NewsTagsReq)(nil),  // 1: pb.NewsTagsReq
	(*NewsTagsResp)(nil), // 2: pb.NewsTagsResp
}
var file_grpc_news_proto_msg_news_tags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_news_proto_msg_news_tags_proto_init() }
func file_grpc_news_proto_msg_news_tags_proto_init() {
	if File_grpc_news_proto_msg_news_tags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_news_proto_msg_news_tags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_news_tags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsTagsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_news_tags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsTagsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_news_proto_msg_news_tags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_news_proto_msg_news_tags_proto_goTypes,
		DependencyIndexes: file_grpc_news_proto_msg_news_tags_proto_depIdxs,
		MessageInfos:      file_grpc_news_proto_msg_news_tags_proto_msgTypes,
	}.Build()
	File_grpc_news_proto_msg_news_tags_proto = out.File
	file_grpc_news_proto_msg_news_tags_proto_rawDesc = nil
	file_grpc_news_proto_msg_news_tags_proto_goTypes = nil
	file_grpc_news_proto_msg_news_tags_proto_depIdxs = nil
}
