// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/news/proto/msg/page_content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content           string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedAt         string `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	UsernameUpdatedBy string `protobuf:"bytes,5,opt,name=UsernameUpdatedBy,proto3" json:"UsernameUpdatedBy,omitempty"`
	NameUpdatedBy     string `protobuf:"bytes,6,opt,name=NameUpdatedBy,proto3" json:"NameUpdatedBy,omitempty"`
	EmailUpdatedBy    string `protobuf:"bytes,7,opt,name=EmailUpdatedBy,proto3" json:"EmailUpdatedBy,omitempty"`
	AvatarUpdatedBy   string `protobuf:"bytes,8,opt,name=AvatarUpdatedBy,proto3" json:"AvatarUpdatedBy,omitempty"`
}

func (x *PageContent) Reset() {
	*x = PageContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContent) ProtoMessage() {}

func (x *PageContent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContent.ProtoReflect.Descriptor instead.
func (*PageContent) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_page_content_proto_rawDescGZIP(), []int{0}
}

func (x *PageContent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PageContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PageContent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PageContent) GetUsernameUpdatedBy() string {
	if x != nil {
		return x.UsernameUpdatedBy
	}
	return ""
}

func (x *PageContent) GetNameUpdatedBy() string {
	if x != nil {
		return x.NameUpdatedBy
	}
	return ""
}

func (x *PageContent) GetEmailUpdatedBy() string {
	if x != nil {
		return x.EmailUpdatedBy
	}
	return ""
}

func (x *PageContent) GetAvatarUpdatedBy() string {
	if x != nil {
		return x.AvatarUpdatedBy
	}
	return ""
}

type PageContentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedBy string `protobuf:"bytes,3,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Page      string `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"` // about_us career newsletter
}

func (x *PageContentReq) Reset() {
	*x = PageContentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContentReq) ProtoMessage() {}

func (x *PageContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContentReq.ProtoReflect.Descriptor instead.
func (*PageContentReq) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_page_content_proto_rawDescGZIP(), []int{1}
}

func (x *PageContentReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PageContentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PageContentReq) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *PageContentReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type PageContentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg         string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	PageContent *PageContent `protobuf:"bytes,3,opt,name=pageContent,proto3" json:"pageContent,omitempty"`
}

func (x *PageContentResp) Reset() {
	*x = PageContentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContentResp) ProtoMessage() {}

func (x *PageContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_news_proto_msg_page_content_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContentResp.ProtoReflect.Descriptor instead.
func (*PageContentResp) Descriptor() ([]byte, []int) {
	return file_grpc_news_proto_msg_page_content_proto_rawDescGZIP(), []int{2}
}

func (x *PageContentResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PageContentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PageContentResp) GetPageContent() *PageContent {
	if x != nil {
		return x.PageContent
	}
	return nil
}

var File_grpc_news_proto_msg_page_content_proto protoreflect.FileDescriptor

var file_grpc_news_proto_msg_page_content_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x91, 0x02, 0x0a,
	0x0b, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x26,
	0x0a, 0x0e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x22, 0x6c, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x6a,
	0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x70,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_news_proto_msg_page_content_proto_rawDescOnce sync.Once
	file_grpc_news_proto_msg_page_content_proto_rawDescData = file_grpc_news_proto_msg_page_content_proto_rawDesc
)

func file_grpc_news_proto_msg_page_content_proto_rawDescGZIP() []byte {
	file_grpc_news_proto_msg_page_content_proto_rawDescOnce.Do(func() {
		file_grpc_news_proto_msg_page_content_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_news_proto_msg_page_content_proto_rawDescData)
	})
	return file_grpc_news_proto_msg_page_content_proto_rawDescData
}

var file_grpc_news_proto_msg_page_content_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_news_proto_msg_page_content_proto_goTypes = []interface{}{
	(*PageContent)(nil),     // 0: pb.PageContent
	(*PageContentReq)(nil),  // 1: pb.PageContentReq
	(*PageContentResp)(nil), // 2: pb.PageContentResp
}
var file_grpc_news_proto_msg_page_content_proto_depIdxs = []int32{
	0, // 0: pb.PageContentResp.pageContent:type_name -> pb.PageContent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_news_proto_msg_page_content_proto_init() }
func file_grpc_news_proto_msg_page_content_proto_init() {
	if File_grpc_news_proto_msg_page_content_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_news_proto_msg_page_content_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_page_content_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageContentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_news_proto_msg_page_content_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageContentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_news_proto_msg_page_content_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_news_proto_msg_page_content_proto_goTypes,
		DependencyIndexes: file_grpc_news_proto_msg_page_content_proto_depIdxs,
		MessageInfos:      file_grpc_news_proto_msg_page_content_proto_msgTypes,
	}.Build()
	File_grpc_news_proto_msg_page_content_proto = out.File
	file_grpc_news_proto_msg_page_content_proto_rawDesc = nil
	file_grpc_news_proto_msg_page_content_proto_goTypes = nil
	file_grpc_news_proto_msg_page_content_proto_depIdxs = nil
}
